### ISSUE TITLE
Is this for Tatkal 

### ISSUE THREAD

**Issue by siddhu2310** [Ruturajsinh2839/woc6-react_js-IRCTC-BOOKING--Ruturajsinh#1]
SI this works for tatkal ticket booking

**Comment by Ruturajsinh2839** [comment]
> SI this works for tatkal ticket booking

No, this is not for Tatkal ticket reservations. I'm currently working on a project using ReactJS and Firebase. It functions similarly to a template, with the ability to book and cancel tickets. I haven't implemented any payment gateways. This is our college event called Winter of Code.
